faq/api/v1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('questions/', views.QuestionView.as_view(), name='questions'),
    path('questions/public/', views.QuestionPublicView.as_view(), name='questions_public'),
    path('questions/waiting/', views.QuestionWaitingView.as_view(), name='questions_waiting'),
    path('questions/<int:pk>', views.get_question, name='question_get'),
    path('questions/reply/<int:pk>', views.reply_question, name='question_reply'),
]

faq/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.QuestionListView.as_view(), name='index'),
    path('add/', views.QuestionCreateView.as_view(), name='add'),
    path('list/', views.question_list_admin, name='list_admin'),
    path('update/<int:pk>/', views.UpdateQuestion.as_view(), name='update'),
]

faqtest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include(('faq.urls', 'faq'), namespace='faq')),
]

urlpatterns += i18n_patterns(
    path('api/v1/', include([
        path('auth/', include('djoser.urls')),
        path('auth/', include('djoser.urls.jwt')),
        path('', include('faq.api.v1.urls')),
    ])),

    prefix_default_language=False
)

faq/models.py
from django.db import models
from django.utils.translation import gettext as _


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Question(models.Model):
    category = models.ForeignKey(Category, verbose_name=_("Catégorie"), on_delete=models.SET_NULL, null=True, related_name='questions')
    question = models.TextField(_('Question'))
    answer = models.TextField(_('Réponse'), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ['-created_at']

faq/api/v1/views.py
from django.db.models import Q
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from faq.models import Question
from .serializers import QuestionSerializer


class QuestionView(APIView):
    serializer_class = QuestionSerializer
    permission_classes = [IsAuthenticated]

    def get_permissions(self):
        if self.request.method == 'POST':
            return [AllowAny()]
        else:
            return [IsAuthenticated()]

    def get(self, request):
        questions = Question.objects.all()
        serialized_questions = self.serializer_class(questions, many=True)
        return Response(serialized_questions.data)

    def post(self, request):
        serialized_question = self.serializer_class(data=request.data)
        if serialized_question.is_valid():
            serialized_question.save()
            return Response(serialized_question.data, status=status.HTTP_201_CREATED)
        return Response(serialized_question.errors, status=status.HTTP_400_BAD_REQUEST)


class QuestionPublicView(APIView):
    serializer_class = QuestionSerializer

    def get(self, request):
        questions = Question.objects.exclude(Q(answer__isnull=True) | Q(answer=''))
        serialized_questions = self.serializer_class(questions, many=True)
        return Response(serialized_questions.data)


class QuestionWaitingView(APIView):
    serializer_class = QuestionSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request):
        questions = Question.objects.filter(Q(answer__isnull=True) | Q(answer=''))
        serialized_questions = self.serializer_class(questions, many=True)
        return Response(serialized_questions.data)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    serializer_class = QuestionSerializer

    if question:
        return Response(serializer_class(question).data)
    else:
        return Response(question)


@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def reply_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    serializer_class = QuestionSerializer

    if question:
        if request.data['answer']:
            question.answer = request.data['answer']
            question.save()
            return Response(serializer_class(question).data)
        else:
            return Response({'answer': 'Field required'})
    else:
        return Response(question)

faq/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .models import Question


appname = 'faq'


class QuestionListView(ListView):
    model = Question

    def get_queryset(self):
        queryset = Question.objects.exclude(Q(answer__isnull=True) | Q(answer=''))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class QuestionCreateView(CreateView):
    model = Question
    fields = [
        'question',
        'category',
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Veuillez entrer votre question')
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, _('Votre question a été enregistrée avec succès'))
        return reverse('faq:index')


@login_required(login_url='/login/')
def question_list_admin(request, template=appname+'/question_list_admin.html'):
    object_list = Question.objects.filter(Q(answer__isnull=True) | Q(answer=''))

    context = {
        'object_list': object_list,
    }

    return render(request, template, context)


class UpdateQuestion(LoginRequiredMixin, UpdateView):
    model = Question
    fields = [
        'answer',
    ]
    template_name_suffix = "_update_form"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Veuillez répondre à la question')
        return context

    def get_success_url(self):
        messages.success(self.request, _('Votre réponse a été enregistrée avec succès'))
        return reverse('faq:list_admin')

templates/_base/base.html
{% load bootstrap5 %}


<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="ChristianNomena">
  <meta name="description" content="Une application de FAQ pour les visiteurs du site web">
  <title>FAQ Web App</title>

  {% bootstrap_css %}
  {% block stylesheet %}
  {% endblock %}
</head>
<body>
  {% include '_base/header.html' %}

  <main class="container">
    {% include '_base/messages.html' %}
    {% block content %}
    {% endblock %}
  </main>

  {% include '_base/footer.html' %}

  {% bootstrap_javascript %}
  {% block scripts %}
  {% endblock %}
</body>
</html>

templates/_base/header.html
{% load i18n %}

<header>
  <nav class="navbar navbar-expand-lg bg-light navbar-fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'faq:index' %}"><strong>FAQ</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'faq:index' %}">{% trans 'Accueil' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq:add' %}">{% trans 'Poser une question' %}</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'faq:list_admin' %}">{% trans 'Répondre aux questions' %}</a>
            </li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
          <a class="nav-link btn btn-danger text-white" href="/logout/">{% trans 'Se déconnecter' %}</a>
        {% else %}
          <a class="nav-link btn btn-primary text-white" href="/login/">{% trans 'Se connecter' %}</a>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

templates/_base/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <div class="alert-message">
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/faq/question_form.html
{% extends '_base/base.html' %}
{% load i18n %}
{% load bootstrap5 %}


{% block content %}
  <div class="row my-4">
    <div class="col">
      <h1 class="text-primary text-center mb-4">{{ title }}</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" name="valid" class="btn btn-primary btn-block">
          {% trans "Valider" %}
        </button>
      </form>
    </div>
  </div>
{% endblock %}

templates/faq/question_list.html
{% extends '_base/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
  <div class="row text-center my-4">
    <div class="col">
      <h1 class="text-primary mb-4">{% trans 'Bienvenue dans notre FAQ' %}</h1>
      <img class="w-50" src="{% static 'images/faq_hero.jpg' %}"  alt="FAQ Hero"/>
    </div>
  </div>
  <div class="row text-center">
    <div class="col">
      <h5 class="text-secondary">{% trans "Il n'y a jamais de question bête" %}</h5>
      <a href="{% url 'faq:add' %}" class="btn btn-primary mt-3">{% trans 'Posez votre question' %}</a>
    </div>
  </div>
  <div class="row my-5">
    <div class="col">
      <h4 class="text-secondary text-center mb-3">{% trans 'Liste de toutes les questions posées' %}</h4>
      <div class="accordion" id="accordionFaq">
        {% for obj in object_list %}
          <div class="accordion-item">
            <h2 class="accordion-header" id="heading{{ obj.id }}">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ obj.id }}" aria-expanded="true" aria-controls="collapse{{ obj.id }}">
                {{ obj.question }}
              </button>
            </h2>
            <div id="collapse{{ obj.id }}" class="accordion-collapse collapse show" aria-labelledby="heading{{ obj.id }}" data-bs-parent="#accordionFaq">
              <div class="accordion-body">
                <div class="mb-3">
                  <h6>{% trans 'Réponse' %}</h6>
                  {{ obj.answer }}
                </div>
                <div>
                  <h6 class="mt-3">{% trans 'Catégorie' %}</h6>
                  {{ obj.category|default_if_none:_("Aucune") }}
                </div>
              </div>
            </div>
          </div>
        {% empty %}
          <p class="text-center">{% trans 'Aucune réponse aux questions pour le moment' %}</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/faq/question_list_admin.html
{% extends '_base/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
  <div class="row text-center my-4">
    <div class="col">
      <h1 class="text-primary">{% trans 'Bienvenue dans votre espace personnel' %} <strong>{{ user }}</strong> !</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h4 class="text-secondary text-center mb-4">{% trans 'Liste des questions non répondues' %}</h4>
      <div class="d-grid gap-3">
        {% for obj in object_list %}
          <div class="card shadow-sm">
            <div class="card-body d-flex justify-content-between align-items-center">
              <div>
                <h6 class="card-title">{{ obj.question }}</h6>
                <p>{% trans 'Catégorie' %} : <span class="text-secondary">{{ obj.category|default_if_none:_("Aucune") }}</span></p>
              </div>
              <div>
                <a class="btn btn-primary" href="{% url 'faq:update' pk=obj.id %}">{% trans 'Répondre' %}</a>
              </div>
            </div>
          </div>
        {% empty %}
          <p class="text-center">{% trans 'Aucune question en attente pour le moment' %}</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/faq/question_update_form.html
{% extends '_base/base.html' %}
{% load i18n %}
{% load bootstrap5 %}


{% block content %}
  <div class="row my-4">
    <div class="col">
      <h1 class="text-primary text-center mb-4">{{ title }}</h1>
      <form method="post">
        {% csrf_token %}
        <div class="card shadow-sm mb-3">
          <div class="card-body d-flex justify-content-between align-items-center">
            <div>
              <h6 class="card-title">{{ object.question }}</h6>
              <p>{% trans 'Catégorie' %} : <span class="text-secondary">{{ object.category }}</span></p>
            </div>
          </div>
        </div>
        {% bootstrap_form form %}
        <button type="submit" name="valid" class="btn btn-primary btn-block">
          {% trans "Répondre" %}
        </button>
      </form>
    </div>
  </div>
{% endblock %}